spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:

          github:
            client-id:
            client-secret:

          facebook:
            client-id:
            client-secret:

#if we can go to github developer account and facebook developer account, we can create the developer account and we can generate the OAuth2 Client-Id